### ISSUE TITLE
Ofelia as scheduler

### ISSUE THREAD

**Issue by t3easy** [t3easy/docker-typo3#30]
Instead of using a cron container, add labels to the php TYPO3 Container to execute TYPO3 scheduler and a config for the schedule to .env.

```yaml
ofelia.enabled: "true"
ofelia.job-exec.typo3-scheduler.schedule: "${TYPO3_SCHEDULER_SCHEDULE}"
ofelia.job-exec.typo3-scheduler.no-overlap: "true"
ofelia.job-exec.typo3-scheduler.user: www-data
ofelia.job-exec.typo3-scheduler.command: typo3 scheduler:run
```

```shell
TYPO3_SCHEDULER_SCHEDULE=@every 15m
```

Also add an optional ofelia service to the stack.
